# Generated by Django 5.0.4 on 2024-05-06 22:06

import Proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to=Proyectos.models.upload_to_actualizacion_media)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to=Proyectos.models.upload_to_actualizacion_media)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('documentacion', models.FileField(blank=True, null=True, upload_to=Proyectos.models.upload_to_proyecto_media)),
                ('videos', models.FileField(blank=True, null=True, upload_to=Proyectos.models.upload_to_proyecto_media)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to=Proyectos.models.upload_to_proyecto_media)),
            ],
        ),
    ]
