# Generated by Django 5.0.4 on 2024-05-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='proyectos_colaborados', to='Usuarios.usern'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='Usuarios.usern'),
        ),
        migrations.AddField(
            model_name='actualizacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto'),
        ),
    ]
