# Generated by Django 5.0.5 on 2024-05-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_initial'),
        ('Usuarios', '0002_remove_usern_carrera_remove_usern_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='proyectos_colaborados', to='Usuarios.userprofile'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='Usuarios.userprofile'),
        ),
    ]
