# Generated by Django 5.0.5 on 2024-05-30 23:57

import Proyectos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_alter_proyecto_creador_proyectocolaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacionproyecto',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='actualizacionproyecto',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='videos',
        ),
        migrations.CreateModel(
            name='ActualizacionProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=Proyectos.models.upload_to_actualizacion_media)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Proyectos.actualizacionproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionProyectoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=Proyectos.models.upload_to_actualizacion_media)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Proyectos.actualizacionproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=Proyectos.models.upload_to_proyecto_media)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=Proyectos.models.upload_to_proyecto_media)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Proyectos.proyecto')),
            ],
        ),
    ]
