# Generated by Django 5.0.5 on 2024-05-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_alter_proyecto_colaboradores_alter_proyecto_creador'),
        ('Usuarios', '0002_remove_usern_carrera_remove_usern_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserN',
        ),
    ]
