# Generated by Django 5.0.5 on 2024-05-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
    ]
