# Generated by Django 5.0.5 on 2024-05-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mostrar_fecha_nacimiento',
            field=models.BooleanField(default=True),
        ),
    ]
